/**难度映射 */
export declare const Level: string[];
export declare const LevelNum: {
    EZ: number;
    HD: number;
    IN: number;
    AT: number;
    LEGACY: number;
};
/**redis路径前缀 */
export declare const redisPath = "phiPlugin";
/**最大难度 */
export declare const MAX_DIFFICULTY = 16.8;
export declare const ChallengeModeName: string[];
export declare const chap: {
    S: string;
    单曲: string;
    单曲精选集: string;
    C0: string;
    旧章: string;
    Legacy: string;
    C5: string;
    霓虹灯牌: string;
    C6: string;
    方舟蜃景: string;
    C7: string;
    时钟链接: string;
    C8: string;
    凌日潮汐: string;
    S1: string;
    忘忧宫: string;
    S2: string;
    弭刻日: string;
    S3: string;
    盗乐行: string;
    S4: string;
    无相乡: string;
    EXS: string;
    极星卫: string;
    黑皇帝: string;
    HYUN: string;
    GOOD: string;
    WAVEAT: string;
    喵斯: string;
    MUSE: string;
    KALPA: string;
    LANOTA: string;
    盘子: string;
    江米条: string;
    姜米條: string;
    茶鸣: string;
    茶鸣拾贰律: string;
    茶鸣十二律: string;
    OverRapid: string;
    OR: string;
    ROTAENO: string;
    方向盘: string;
    CHUNITHM: string;
    中二: string;
    范式: string;
    SHINOBI: string;
    千恋万花: string;
    TAKUMI: string;
    塔库米: string;
    三次方: string;
    节奏大师: string;
    齐秦太帅: string;
    JZDS: string;
};
